#!/usr/bin/env python3
"""Prepare a no-upload Hugging Face Jobs handoff for agentic LoRA training.

The generated bundle is inert. ``upload_to_hub.py`` performs the first network
write when a user explicitly runs it; the resulting ``job_request.json`` is
then suitable for submission through the Hugging Face Jobs integration.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def job_script(dataset_repo: str) -> str:
    return f'''# /// script
# dependencies = [
#   "accelerate>=1,<2",
#   "datasets>=3,<5",
#   "huggingface-hub>=0.30,<2",
#   "peft>=0.15,<1",
#   "torch>=2.5,<3",
#   "trackio>=0.2,<1",
#   "transformers>=4.50,<6",
#   "trl>=0.17,<1",
# ]
# ///
"""Immutable-revision Hugging Face Jobs entry point generated by Flight Recorder."""

import argparse
import subprocess
import sys
from pathlib import Path

from huggingface_hub import snapshot_download


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset-revision", required=True)
    parser.add_argument("--hub-model-id", required=True)
    parser.add_argument("--mode", default="fr_sft_dpo")
    args = parser.parse_args()
    snapshot = Path(snapshot_download(repo_id={dataset_repo!r}, repo_type="dataset", revision=args.dataset_revision))
    command = [
        sys.executable,
        str(snapshot / "runtime" / "train_agentic_lora.py"),
        "--mode", args.mode,
        "--experiment-dir", str(snapshot),
        "--output-dir", str(Path("/tmp") / "hfr-agentic-adapters"),
        "--model-manifest", str(snapshot / "model_manifest.json"),
        "--dataset-manifest", str(snapshot / "dataset_training_manifest.json"),
        "--require-registered-inputs",
        "--push-to-hub",
        "--hub-model-id", args.hub_model_id,
    ]
    return subprocess.run(command, check=False).returncode


if __name__ == "__main__":
    raise SystemExit(main())
'''


def upload_script(dataset_repo: str, private: bool) -> str:
    return f'''# /// script
# dependencies = ["huggingface-hub>=0.30,<2"]
# ///
"""Upload the reviewed payload and bind the Jobs request to its immutable commit."""

import json
from pathlib import Path
from huggingface_hub import HfApi

ROOT = Path(__file__).resolve().parent
PAYLOAD = ROOT / "payload"
api = HfApi()
api.create_repo(repo_id={dataset_repo!r}, repo_type="dataset", private={private!r}, exist_ok=True)
commit = api.upload_folder(repo_id={dataset_repo!r}, repo_type="dataset", folder_path=PAYLOAD, commit_message="Publish Flight Recorder agentic training handoff")
revision = str(commit.oid)
request = json.loads((ROOT / "job_request.template.json").read_text(encoding="utf-8"))
request["script"] = request["script"].replace("REPLACE_WITH_DATASET_COMMIT", revision)
request["script_args"] = [revision if value == "REPLACE_WITH_DATASET_COMMIT" else value for value in request["script_args"]]
(ROOT / "job_request.json").write_text(json.dumps(request, indent=2, sort_keys=True) + "\\n", encoding="utf-8")
print(json.dumps({{"dataset_repo": {dataset_repo!r}, "revision": revision, "job_request": str(ROOT / "job_request.json")}}, indent=2))
'''


def prepare(args: argparse.Namespace) -> dict[str, Any]:
    experiment = args.experiment_dir.resolve()
    dataset_manifest_path = experiment / "dataset_training_manifest.json"
    if not dataset_manifest_path.exists():
        raise ValueError("experiment is missing dataset_training_manifest.json; run build_agentic_finetune_experiment.py first")
    model_manifest = read_json(args.model_manifest)
    if not model_manifest.get("model_id"):
        raise ValueError("model manifest must declare model_id")
    license_record = model_manifest.get("license") if isinstance(model_manifest.get("license"), dict) else {}
    license_status = str(model_manifest.get("license_status") or license_record.get("status") or "").lower()
    if license_status in {"", "unknown", "unreviewed", "pending", "blocked", "rejected", "disallowed"}:
        raise ValueError("model manifest must record an approved/known license status")
    training_allowed = model_manifest.get(
        "training_allowed",
        model_manifest.get("fine_tuning_allowed", license_record.get("allow_training", True)),
    )
    if training_allowed is not True:
        raise ValueError("model manifest must explicitly allow training")

    out = args.out.resolve()
    if out.exists() and any(out.iterdir()):
        raise ValueError(f"output directory is not empty: {out}")
    payload = out / "payload"
    (payload / "runtime").mkdir(parents=True, exist_ok=True)
    shutil.copytree(experiment / "data", payload / "data")
    sanitized_dataset_manifest = read_json(dataset_manifest_path)
    sanitized_dataset_manifest.pop("source_manifest", None)
    write_json(payload / "dataset_training_manifest.json", sanitized_dataset_manifest)
    write_json(payload / "model_manifest.json", model_manifest)
    shutil.copy2(ROOT / "scripts" / "train_agentic_lora.py", payload / "runtime" / "train_agentic_lora.py")
    (payload / "runtime" / "hf_job.py").write_text(job_script(args.dataset_repo), encoding="utf-8")

    request = {
        "script": f"https://huggingface.co/datasets/{args.dataset_repo}/resolve/REPLACE_WITH_DATASET_COMMIT/runtime/hf_job.py",
        "script_args": [
            "--dataset-revision",
            "REPLACE_WITH_DATASET_COMMIT",
            "--hub-model-id",
            args.hub_model_id,
            "--mode",
            args.mode,
        ],
        "flavor": args.flavor,
        "timeout": args.timeout,
        "secrets": {"HF_TOKEN": "$HF_TOKEN"},
    }
    write_json(out / "job_request.template.json", request)
    (out / "upload_to_hub.py").write_text(upload_script(args.dataset_repo, args.private), encoding="utf-8")

    fingerprints = {
        path.relative_to(payload).as_posix(): {
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        }
        for path in sorted(payload.rglob("*"))
        if path.is_file()
    }
    handoff = {
        "schema_version": "hfr.huggingface_jobs_handoff.v1",
        "provider": "huggingface_jobs",
        "submitted": False,
        "network_writes_performed": False,
        "dataset_repo": args.dataset_repo,
        "hub_model_id": args.hub_model_id,
        "mode": args.mode,
        "flavor": args.flavor,
        "timeout": args.timeout,
        "payload_fingerprints": fingerprints,
        "upload_command": f"uv run {out / 'upload_to_hub.py'}",
        "submission": {
            "tool": "hf_jobs",
            "operation": "uv",
            "request_template": str(out / "job_request.template.json"),
            "request_after_upload": str(out / "job_request.json"),
            "requires_explicit_paid_network_approval": True,
        },
        "checks": {
            "dataset_manifest_present": True,
            "model_license_known": True,
            "model_training_allowed": True,
            "hub_destination_declared": bool(args.hub_model_id),
            "hf_token_secret_reference_present": True,
            "checkpoint_and_final_push_enabled": True,
        },
    }
    write_json(out / "handoff.json", handoff)
    (out / "README.md").write_text(
        "# Hugging Face Jobs handoff\n\n"
        "1. Review `payload/`, `handoff.json`, and the model/dataset licenses.\n"
        "2. With explicit approval for the upload, run the recorded `upload_command`.\n"
        "3. Submit the generated `job_request.json` through the Hugging Face Jobs integration.\n"
        "4. The job pushes every checkpoint and the final adapter to the declared model repository.\n",
        encoding="utf-8",
    )
    return handoff


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--experiment-dir", type=Path, required=True)
    parser.add_argument("--model-manifest", type=Path, required=True)
    parser.add_argument("--dataset-repo", required=True, help="Hugging Face dataset repo, e.g. username/hermes-agentic-data")
    parser.add_argument("--hub-model-id", required=True, help="Destination Hub model repo for checkpoints and adapter")
    parser.add_argument("--mode", choices=["fr_sft", "fr_action_sft", "fr_dpo", "fr_sft_dpo"], default="fr_sft_dpo")
    parser.add_argument("--flavor", default="a10g-large")
    parser.add_argument("--timeout", default="4h")
    parser.add_argument("--private", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--out", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    handoff = prepare(parse_args())
    print(json.dumps(handoff, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
