#!/usr/bin/env python3
"""Prepare an immutable, private-by-default Hugging Face Jobs lifecycle.

This command is side-effect free. It packages a reviewed trainer plan and
writes an upload helper; the helper performs the first network write only when
an operator explicitly runs the recorded command.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from flightrecorder.huggingface_lifecycle import (  # noqa: E402
    EXACT_DEPENDENCIES,
    HF_JOBS_HANDOFF_SCHEMA_VERSION,
    HuggingFaceLifecycleError,
    artifact_set_sha256,
    attach_identity,
    build_reviewed_training_plan,
    file_record,
    sha256_file,
    utc_now,
    validate_reviewed_training_plan,
)


TRAINER = ROOT / "scripts" / "train_agentic_lora.py"
LIFECYCLE_MODULE = ROOT / "flightrecorder" / "huggingface_lifecycle.py"


def read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def job_script(dataset_repo: str, dependencies: list[str]) -> str:
    dependency_lines = "\n".join(f'#   "{item}",' for item in dependencies)
    template = r'''# /// script
# dependencies = [
__DEPENDENCIES__
# ]
# ///
"""Immutable-plan Hugging Face Jobs runner generated by Flight Recorder."""

import argparse
import json
import os
import shutil
import signal
import subprocess
import sys
import traceback
from pathlib import Path

from huggingface_hub import HfApi, snapshot_download

from huggingface_lifecycle import (
    HuggingFaceLifecycleError,
    build_job_completion,
    build_publication_receipt,
    file_record,
    observe_runtime_identity,
    runtime_declaration_from_plan,
    sha256_file,
    trainer_argv_from_plan,
    validate_job_completion,
    validate_reviewed_training_plan,
)


DATASET_REPO = __DATASET_REPO__


def read_json(path):
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise HuggingFaceLifecycleError(f"Expected JSON object: {path}")
    return value


def write_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def artifact_record(path, root, role, repo_prefix):
    row = file_record(path, base_dir=root, role=role)
    row["path"] = f"{repo_prefix}/{row['path']}"
    return row


def materialize_resume(plan, model_repo, work_root):
    resume = plan["resume"]
    if resume["enabled"] is not True:
        return None
    snapshot = Path(
        snapshot_download(
            repo_id=model_repo,
            repo_type="model",
            revision=resume["revision"],
        )
    )
    checkpoint = snapshot / resume["checkpoint_path"]
    manifest = checkpoint / "trainer_state.json"
    if not checkpoint.exists() or not checkpoint.is_dir():
        raise HuggingFaceLifecycleError("resume checkpoint directory is missing")
    if not manifest.exists() or sha256_file(manifest) != resume["checkpoint_manifest_sha256"]:
        raise HuggingFaceLifecycleError("resume checkpoint manifest fingerprint mismatch")
    target = work_root / "resume_checkpoint"
    shutil.copytree(checkpoint, target)
    return target


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset-revision", required=True)
    parser.add_argument("--reviewed-plan", default="reviewed_training_plan.json")
    parser.add_argument("--reviewed-plan-sha256", required=True)
    parser.add_argument("--job-id", default="")
    args = parser.parse_args()
    if len(args.dataset_revision) < 40 or not all(char in "0123456789abcdef" for char in args.dataset_revision):
        raise SystemExit("--dataset-revision must be an immutable Hub commit")

    snapshot = Path(snapshot_download(repo_id=DATASET_REPO, repo_type="dataset", revision=args.dataset_revision))
    plan_path = snapshot / args.reviewed_plan
    if sha256_file(plan_path) != args.reviewed_plan_sha256:
        raise SystemExit("reviewed plan file fingerprint mismatch")
    plan = read_json(plan_path)
    errors = validate_reviewed_training_plan(plan, snapshot)
    if errors:
        raise SystemExit("reviewed plan validation failed: " + "; ".join(errors))

    output = plan["output"]
    runtime = plan["runtime"]
    model_repo = output["model_repo"]
    api = HfApi(token=os.environ.get("HF_TOKEN"))
    api.create_repo(repo_id=model_repo, repo_type="model", private=True, exist_ok=True)
    work_root = Path("/tmp") / f"hfr-{plan['identity']['sha256'][:12]}"
    repo_prefix = f"lifecycle/{plan['identity']['sha256'][:16]}"
    trainer_out = work_root / "trainer"
    lifecycle_out = work_root / repo_prefix
    trainer_out.mkdir(parents=True, exist_ok=True)
    lifecycle_out.mkdir(parents=True, exist_ok=True)
    stdout_path = lifecycle_out / "trainer.stdout.log"
    stderr_path = lifecycle_out / "trainer.stderr.log"
    result_registry = trainer_out / "training_registry_events.jsonl"
    registry_link_plan = trainer_out / "model_registry_link_plan.json"
    resume_checkpoint = materialize_resume(plan, model_repo, work_root)
    command = trainer_argv_from_plan(
        plan,
        python=sys.executable,
        trainer_script=snapshot / "runtime" / "train_agentic_lora.py",
        experiment_dir=snapshot,
        output_dir=trainer_out,
        model_manifest=snapshot / "model_manifest.json",
        dataset_manifest=snapshot / "dataset_training_manifest.json",
        result_registry=result_registry,
        model_registry_link_plan=registry_link_plan,
        resume_checkpoint=resume_checkpoint,
    )
    write_json(lifecycle_out / "trainer_argv.json", {"argv": command, "plan_identity": plan["identity"]})
    shutil.copy2(plan_path, lifecycle_out / "reviewed_training_plan.json")

    interrupted = {"value": False}
    runtime_declaration = runtime_declaration_from_plan(plan)
    runtime_observation = observe_runtime_identity(
        runtime["dependencies"],
        context="training_job",
        trainer_script_path=snapshot / "runtime" / "train_agentic_lora.py",
    )
    observed_dependencies = runtime_observation["dependencies"]

    def handle_term(_signum, _frame):
        interrupted["value"] = True
        raise InterruptedError("training job received termination signal")

    signal.signal(signal.SIGTERM, handle_term)
    exit_code = 1
    failure = None
    expected_dependencies = {item.split("==", 1)[0]: item.split("==", 1)[1] for item in runtime_declaration["dependencies"]}
    dependency_drift = sorted(
        name for name, expected in expected_dependencies.items()
        if observed_dependencies.get(name, {}).get("actual") != expected
    )
    if dependency_drift:
        exit_code = 78
        failure = {
            "class": "runtime_identity",
            "message": "installed dependency versions differ from the reviewed lock: " + ", ".join(dependency_drift),
            "retryable": False,
        }
        stdout_path.write_text("", encoding="utf-8")
        stderr_path.write_text(failure["message"] + "\n", encoding="utf-8")
    else:
        try:
            with stdout_path.open("wb") as stdout_handle, stderr_path.open("wb") as stderr_handle:
                completed = subprocess.run(command, stdout=stdout_handle, stderr=stderr_handle, check=False)
            exit_code = int(completed.returncode)
        except (KeyboardInterrupt, InterruptedError) as exc:
            interrupted["value"] = True
            exit_code = 130
            failure = {"class": "interrupted", "message": str(exc), "retryable": True}
        except BaseException as exc:
            exit_code = 1
            failure = {"class": "runner", "message": str(exc), "retryable": True, "traceback": traceback.format_exc()}

    trainer_result_path = trainer_out / f"{plan['trainer']['mode']}_result.json"
    trainer_plan_path = trainer_out / f"{plan['trainer']['mode']}_plan.json"
    trainer_result = read_json(trainer_result_path) if trainer_result_path.exists() else {}
    if interrupted["value"]:
        status = "interrupted"
    elif exit_code == 0 and trainer_result.get("status") == "succeeded":
        status = "completed"
    else:
        status = "failed"
        if failure is None:
            failure = trainer_result.get("failure") or {
                "class": "trainer",
                "message": f"trainer exited with code {exit_code}",
                "retryable": True,
            }

    metrics_path = lifecycle_out / "training_metrics.json"
    write_json(
        metrics_path,
        {"sft": trainer_result.get("sft_train_result"), "dpo": trainer_result.get("dpo_train_result")},
    )
    adapter_manifest_path = lifecycle_out / "adapter_manifest.json"
    write_json(adapter_manifest_path, trainer_result.get("final_adapter_artifacts") or {})
    if trainer_result_path.exists():
        shutil.copy2(trainer_result_path, lifecycle_out / "training_result.json")
    else:
        write_json(lifecycle_out / "training_result.json", {"status": status, "failure": failure})
    if trainer_plan_path.exists():
        shutil.copy2(trainer_plan_path, lifecycle_out / "trainer_generated_plan.json")
    if result_registry.exists():
        shutil.copy2(result_registry, lifecycle_out / result_registry.name)
    if registry_link_plan.exists():
        shutil.copy2(registry_link_plan, lifecycle_out / registry_link_plan.name)

    final_adapter_dir = Path(str(trainer_result.get("final_adapter_dir") or ""))
    if final_adapter_dir.is_dir():
        shutil.copytree(final_adapter_dir, lifecycle_out / "adapter", dirs_exist_ok=True)
    checkpoints = sorted(
        (path for path in trainer_out.rglob("checkpoint-*") if path.is_dir()),
        key=lambda path: path.stat().st_mtime_ns,
    )
    resume_checkpoint_dir = None
    if checkpoints:
        resume_checkpoint_dir = lifecycle_out / "resume_checkpoint"
        shutil.copytree(checkpoints[-1], resume_checkpoint_dir, dirs_exist_ok=True)

    role_paths = {
        "training_plan": lifecycle_out / "reviewed_training_plan.json",
        "trainer_log": stdout_path,
        "trainer_error_log": stderr_path,
        "training_metrics": metrics_path,
        "adapter_manifest": adapter_manifest_path,
        "training_result": lifecycle_out / "training_result.json",
        "trainer_argv": lifecycle_out / "trainer_argv.json",
    }
    artifacts = [artifact_record(path, lifecycle_out, role, repo_prefix) for role, path in role_paths.items()]
    for path in sorted((lifecycle_out / "adapter").rglob("*")) if (lifecycle_out / "adapter").is_dir() else []:
        if path.is_file():
            artifacts.append(artifact_record(path, lifecycle_out, "adapter", repo_prefix))
    if resume_checkpoint_dir is not None:
        for path in sorted(resume_checkpoint_dir.rglob("*")):
            if path.is_file():
                artifacts.append(artifact_record(path, lifecycle_out, "checkpoint", repo_prefix))
    artifact_commit = api.upload_folder(
        repo_id=model_repo,
        repo_type="model",
        folder_path=lifecycle_out,
        path_in_repo=repo_prefix,
        commit_message=f"Persist Flight Recorder lifecycle artifacts ({status})",
    )
    artifact_revision = str(artifact_commit.oid)
    reviewed_plan_record = next(row for row in artifacts if row["role"] == "training_plan")
    publication = build_publication_receipt(
        repo_id=model_repo,
        repo_type="model",
        revision=artifact_revision,
        artifacts=artifacts,
        private=True,
        source_plan_sha256=plan["identity"]["sha256"],
        reviewed_plan_record=reviewed_plan_record,
        runtime_declaration=runtime_declaration,
        runtime_observation=runtime_observation,
        base_dir=work_root,
    )
    resume_state = dict(plan["resume"])
    if status != "completed" and resume_checkpoint_dir is not None:
        trainer_state = resume_checkpoint_dir / "trainer_state.json"
        if not trainer_state.is_file():
            raise HuggingFaceLifecycleError("latest checkpoint has no trainer_state.json")
        mode = plan["trainer"]["mode"]
        phase = "dpo" if mode in {"fr_dpo", "fr_sft_dpo"} else "sft"
        resume_state = {
            "enabled": True,
            "phase": phase,
            "revision": artifact_revision,
            "checkpoint_path": f"{repo_prefix}/resume_checkpoint",
            "checkpoint_manifest_sha256": sha256_file(trainer_state),
        }
    resume_state.update({"available_after_run": status != "completed" and resume_state.get("enabled") is True, "artifact_revision": artifact_revision})
    completion = build_job_completion(
        status=status,
        plan_record=reviewed_plan_record,
        dataset_revision=args.dataset_revision,
        job_id=args.job_id or os.environ.get("HF_JOB_ID") or "unreported-hf-job",
        exit_code=exit_code,
        artifacts=artifacts,
        publication_receipt=publication,
        runtime_declaration=runtime_declaration,
        runtime_observation=runtime_observation,
        resume=resume_state,
        failure=failure,
        base_dir=work_root,
    )
    errors = validate_job_completion(completion, work_root)
    if errors:
        raise HuggingFaceLifecycleError("generated completion receipt is invalid: " + "; ".join(errors))
    publication_path = lifecycle_out / "publication_receipt.json"
    completion_path = lifecycle_out / "completion_receipt.json"
    write_json(publication_path, publication)
    write_json(completion_path, completion)
    receipt_commit = api.upload_folder(
        repo_id=model_repo,
        repo_type="model",
        folder_path=lifecycle_out,
        path_in_repo=repo_prefix,
        commit_message=f"Publish Flight Recorder completion receipt ({status})",
    )
    print(
        json.dumps(
            {
                "status": status,
                "job_id": completion["job"]["job_id"],
                "artifact_revision": artifact_revision,
                "completion_revision": str(receipt_commit.oid),
                "completion_path": f"{repo_prefix}/completion_receipt.json",
            },
            sort_keys=True,
        )
    )
    return 0 if status == "completed" else exit_code or 1


if __name__ == "__main__":
    raise SystemExit(main())
'''
    return template.replace("__DEPENDENCIES__", dependency_lines).replace("__DATASET_REPO__", repr(dataset_repo))


def upload_script(dataset_repo: str, private: bool) -> str:
    template = r'''# /// script
# dependencies = ["huggingface-hub==1.1.5"]
# ///
"""Publish a reviewed private payload and bind the request to immutable commits."""

import json
import sys
from pathlib import Path

from huggingface_hub import HfApi

ROOT = Path(__file__).resolve().parent
PAYLOAD = ROOT / "payload"
sys.path.insert(0, str(PAYLOAD / "runtime"))
from huggingface_lifecycle import (  # noqa: E402
    build_publication_receipt,
    file_record,
    observe_runtime_identity,
    runtime_declaration_from_plan,
)

api = HfApi()
api.create_repo(repo_id=__DATASET_REPO__, repo_type="dataset", private=__PRIVATE__, exist_ok=True)
commit = api.upload_folder(
    repo_id=__DATASET_REPO__,
    repo_type="dataset",
    folder_path=PAYLOAD,
    commit_message="Publish reviewed Flight Recorder agentic training handoff",
)
artifact_revision = str(commit.oid)
plan = json.loads((PAYLOAD / "reviewed_training_plan.json").read_text(encoding="utf-8"))
runtime = plan["runtime"]
runtime_declaration = runtime_declaration_from_plan(plan)
runtime_observation = observe_runtime_identity(
    runtime["dependencies"],
    context="payload_publisher",
    trainer_script_path=PAYLOAD / "runtime" / "train_agentic_lora.py",
)
artifacts = []
for path in sorted(PAYLOAD.rglob("*")):
    if path.is_file() and path.name != "dataset_publication_receipt.json":
        artifacts.append(file_record(path, base_dir=PAYLOAD, role="training_payload"))
receipt = build_publication_receipt(
    repo_id=__DATASET_REPO__,
    repo_type="dataset",
    revision=artifact_revision,
    artifacts=artifacts,
    private=__PRIVATE__,
    source_plan_sha256=plan["identity"]["sha256"],
    reviewed_plan_record=file_record(
        PAYLOAD / "reviewed_training_plan.json",
        base_dir=PAYLOAD,
        role="reviewed_training_plan",
    ),
    runtime_declaration=runtime_declaration,
    runtime_observation=runtime_observation,
    base_dir=PAYLOAD,
)
(PAYLOAD / "dataset_publication_receipt.json").write_text(
    json.dumps(receipt, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)
receipt_commit = api.upload_file(
    repo_id=__DATASET_REPO__,
    repo_type="dataset",
    path_or_fileobj=PAYLOAD / "dataset_publication_receipt.json",
    path_in_repo="dataset_publication_receipt.json",
    commit_message="Publish private dataset revision receipt",
)
revision = str(receipt_commit.oid)
request = json.loads((ROOT / "job_request.template.json").read_text(encoding="utf-8"))
request["script"] = request["script"].replace("REPLACE_WITH_DATASET_COMMIT", revision)
request["script_args"] = [revision if value == "REPLACE_WITH_DATASET_COMMIT" else value for value in request["script_args"]]
(ROOT / "job_request.json").write_text(json.dumps(request, indent=2, sort_keys=True) + "\n", encoding="utf-8")
(ROOT / "dataset_publication_receipt.json").write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(json.dumps({"dataset_repo": __DATASET_REPO__, "artifact_revision": artifact_revision, "completion_revision": revision, "job_request": str(ROOT / "job_request.json")}, indent=2))
'''
    return template.replace("__DATASET_REPO__", repr(dataset_repo)).replace("__PRIVATE__", repr(private))


def _validate_model_manifest(model_manifest: dict[str, Any]) -> None:
    if model_manifest.get("schema_version") != "hfr.model_candidate.v1":
        raise ValueError("model manifest must use hfr.model_candidate.v1")
    if not model_manifest.get("candidate_id") or not model_manifest.get("model_id"):
        raise ValueError("model manifest must declare candidate_id and model_id")
    source = model_manifest.get("source") if isinstance(model_manifest.get("source"), dict) else {}
    revision = str(source.get("revision") or "")
    if len(revision) < 40 or not all(char in "0123456789abcdef" for char in revision):
        raise ValueError("model manifest source.revision must be an immutable commit")
    license_record = model_manifest.get("license") if isinstance(model_manifest.get("license"), dict) else {}
    if (
        license_record.get("status") != "approved"
        or license_record.get("review_status") != "approved"
        or license_record.get("accepted_terms") is not True
        or license_record.get("training_allowed") is not True
    ):
        raise ValueError("model manifest license must be explicitly reviewed and approved for training")
    compatibility = model_manifest.get("compatibility") if isinstance(model_manifest.get("compatibility"), dict) else {}
    tokenizer = compatibility.get("tokenizer") if isinstance(compatibility.get("tokenizer"), dict) else {}
    chat_template = compatibility.get("chat_template") if isinstance(compatibility.get("chat_template"), dict) else {}
    tokenizer_revision = str(tokenizer.get("revision") or "")
    if len(tokenizer_revision) < 40 or not all(char in "0123456789abcdef" for char in tokenizer_revision):
        raise ValueError("model manifest compatibility.tokenizer.revision must be an immutable commit")
    chat_template_sha256 = str(chat_template.get("sha256") or "")
    if len(chat_template_sha256) != 64 or not all(char in "0123456789abcdef" for char in chat_template_sha256):
        raise ValueError("model manifest compatibility.chat_template.sha256 is required")


def _validate_source_plan(
    plan: dict[str, Any],
    model_manifest: dict[str, Any],
    dataset_manifest: dict[str, Any],
    mode: str | None,
) -> None:
    if plan.get("schema_version") != "hfr.agentic_lora_training_plan.v1":
        raise ValueError("--training-plan must be an hfr.agentic_lora_training_plan.v1 artifact")
    if plan.get("passed") is not True or plan.get("recommendation") != "launch_allowed":
        raise ValueError("--training-plan must be passing and launch_allowed")
    if plan.get("model") != model_manifest.get("model_id"):
        raise ValueError("training plan model must match the immutable model manifest")
    if mode and mode != plan.get("mode"):
        raise ValueError("--mode must match the reviewed training plan")
    tracking = plan.get("tracking") if isinstance(plan.get("tracking"), dict) else {}
    if tracking.get("report_to") != ["trackio"]:
        raise ValueError("reviewed training plan must enable Trackio")
    if str(plan.get("mode") or "").startswith("fr_"):
        evidence = plan.get("control_evidence") if isinstance(plan.get("control_evidence"), dict) else {}
        artifacts = evidence.get("artifacts") if isinstance(evidence.get("artifacts"), dict) else {}
        expected_controls = {
            "governance_receipt", "contamination_report", "curated_dataset",
            "action_credit", "branch_replay", "reviewed_preferences",
        }
        if (
            evidence.get("required") is not True
            or evidence.get("passed") is not True
            or evidence.get("failures") != []
            or set(artifacts) != expected_controls
        ):
            raise ValueError("Flight Recorder source plan must carry replayed content-bound control evidence")
        checks = {
            str(row.get("id")): row.get("passed")
            for row in plan.get("checks", [])
            if isinstance(row, dict)
        }
        if checks.get("content_bound_control_artifacts_replayed") is not True or checks.get(
            "training_rows_bound_to_control_artifacts"
        ) is not True:
            raise ValueError("Flight Recorder source plan did not pass content and row control replay")
        manifest_records = dataset_manifest.get("artifact_fingerprints")
        if not isinstance(manifest_records, dict):
            raise ValueError("dataset manifest has no artifact fingerprints")
        for name in sorted(expected_controls):
            plan_record = artifacts.get(name) if isinstance(artifacts.get(name), dict) else {}
            manifest_record = manifest_records.get(name) if isinstance(manifest_records.get(name), dict) else {}
            if (
                plan_record.get("sha256") != manifest_record.get("sha256")
                or plan_record.get("size_bytes") != manifest_record.get("size_bytes")
            ):
                raise ValueError(f"source plan control evidence does not match dataset manifest: {name}")


def prepare(args: argparse.Namespace) -> dict[str, Any]:
    experiment = args.experiment_dir.resolve()
    dataset_manifest_path = experiment / "dataset_training_manifest.json"
    if not dataset_manifest_path.exists():
        raise ValueError("experiment is missing dataset_training_manifest.json; run build_agentic_finetune_experiment.py first")
    source_plan_path = args.training_plan.resolve()
    model_manifest_path = args.model_manifest.resolve()
    source_plan = read_json(source_plan_path)
    model_manifest = read_json(model_manifest_path)
    dataset_manifest = read_json(dataset_manifest_path)
    _validate_model_manifest(model_manifest)
    _validate_source_plan(source_plan, model_manifest, dataset_manifest, args.mode)
    dependencies = list(args.dependency or EXACT_DEPENDENCIES)

    out = args.out.resolve()
    if out.exists() and any(out.iterdir()):
        raise ValueError(f"output directory is not empty: {out}")
    payload = out / "payload"
    (payload / "runtime").mkdir(parents=True, exist_ok=True)
    (payload / "reviewed").mkdir(parents=True, exist_ok=True)
    shutil.copytree(experiment / "data", payload / "data")
    controls_source = experiment / "controls"
    if not controls_source.is_dir():
        raise ValueError("experiment is missing content-bound controls required by Flight Recorder training")
    shutil.copytree(controls_source, payload / "controls")
    sanitized_dataset_manifest = dataset_manifest
    sanitized_dataset_manifest.pop("source_manifest", None)
    write_json(payload / "dataset_training_manifest.json", sanitized_dataset_manifest)
    write_json(payload / "model_manifest.json", model_manifest)
    shutil.copy2(TRAINER, payload / "runtime" / "train_agentic_lora.py")
    shutil.copy2(LIFECYCLE_MODULE, payload / "runtime" / "huggingface_lifecycle.py")
    write_json(payload / "reviewed" / "source_training_plan.json", source_plan)

    data_artifacts = [
        file_record(path, base_dir=payload, role="training_data")
        for directory in (payload / "data", payload / "controls")
        for path in sorted(directory.rglob("*"))
        if path.is_file()
    ]
    reviewed_plan = build_reviewed_training_plan(
        source_plan=source_plan,
        source_plan_record=file_record(
            payload / "reviewed" / "source_training_plan.json", base_dir=payload, role="source_training_plan"
        ),
        model_manifest=model_manifest,
        model_manifest_record=file_record(payload / "model_manifest.json", base_dir=payload, role="model_manifest"),
        dataset_manifest_record=file_record(
            payload / "dataset_training_manifest.json", base_dir=payload, role="dataset_manifest"
        ),
        trainer_script_record=file_record(
            payload / "runtime" / "train_agentic_lora.py", base_dir=payload, role="trainer_script"
        ),
        data_artifacts=data_artifacts,
        reviewer=args.reviewer,
        reviewed_at=args.reviewed_at or utc_now(),
        dataset_repo=args.dataset_repo,
        model_repo=args.hub_model_id,
        flavor=args.flavor,
        timeout=args.timeout,
        container_image=args.container_image,
        dependencies=dependencies,
        private=args.private,
        resume={
            "enabled": bool(args.resume_revision),
            "phase": args.resume_phase,
            "revision": args.resume_revision,
            "checkpoint_path": args.resume_checkpoint_path,
            "checkpoint_manifest_sha256": args.resume_checkpoint_manifest_sha256,
        },
    )
    plan_path = payload / "reviewed_training_plan.json"
    write_json(plan_path, reviewed_plan)
    plan_errors = validate_reviewed_training_plan(reviewed_plan, payload)
    if plan_errors:
        raise HuggingFaceLifecycleError("reviewed plan did not replay after packaging: " + "; ".join(plan_errors))
    (payload / "runtime" / "hf_job.py").write_text(job_script(args.dataset_repo, dependencies), encoding="utf-8")

    payload_records = [
        file_record(path, base_dir=payload, role="payload")
        for path in sorted(payload.rglob("*"))
        if path.is_file()
    ]
    write_json(
        payload / "payload_manifest.json",
        {
            "schema_version": "hfr.huggingface_payload_manifest.v1",
            "artifact_count": len(payload_records),
            "artifact_set_sha256": artifact_set_sha256(payload_records),
            "artifacts": payload_records,
        },
    )
    payload_records.append(file_record(payload / "payload_manifest.json", base_dir=payload, role="payload_manifest"))
    plan_sha256 = sha256_file(plan_path)
    request = {
        "script": f"https://huggingface.co/datasets/{args.dataset_repo}/resolve/REPLACE_WITH_DATASET_COMMIT/runtime/hf_job.py",
        "script_args": [
            "--dataset-revision",
            "REPLACE_WITH_DATASET_COMMIT",
            "--reviewed-plan",
            "reviewed_training_plan.json",
            "--reviewed-plan-sha256",
            plan_sha256,
        ],
        "flavor": reviewed_plan["runtime"]["hardware_flavor"],
        "timeout": reviewed_plan["runtime"]["timeout"],
        "image": reviewed_plan["runtime"]["container_image"],
        "secrets": {"HF_TOKEN": "$HF_TOKEN"},
    }
    write_json(out / "job_request.template.json", request)
    (out / "upload_to_hub.py").write_text(upload_script(args.dataset_repo, args.private), encoding="utf-8")

    handoff = attach_identity(
        {
            "schema_version": HF_JOBS_HANDOFF_SCHEMA_VERSION,
            "created_at": utc_now(),
            "provider": "huggingface_jobs",
            "submitted": False,
            "network_writes_performed": False,
            "reviewed_plan": file_record(plan_path, base_dir=out, role="reviewed_training_plan"),
            "reviewed_plan_identity": reviewed_plan["identity"],
            "payload_artifact_count": len(payload_records),
            "payload_artifact_set_sha256": artifact_set_sha256(payload_records),
            "payload_artifacts": payload_records,
            "runtime": reviewed_plan["runtime"],
            "output": reviewed_plan["output"],
            "resume": reviewed_plan["resume"],
            "upload_command": f"uv run {out / 'upload_to_hub.py'}",
            "submission": {
                "tool": "hf_jobs",
                "operation": "uv",
                "request_template": str(out / "job_request.template.json"),
                "request_after_upload": str(out / "job_request.json"),
                "requires_explicit_paid_network_approval": True,
            },
            "canonical_completion": {
                "remote_path": reviewed_plan["output"]["result_path"],
                "import_requires_immutable_completion_revision": True,
                "canonical_artifacts": [
                    "hfr.agentic_training_result.v1",
                    "hfr.cloud_training_completion_receipt.v1",
                ],
            },
            "checks": {
                "reviewed_plan_replayed": True,
                "trainer_arguments_derive_only_from_plan": True,
                "immutable_model_tokenizer_and_template": True,
                "dependencies_exactly_locked": True,
                "private_dataset_and_model_repositories": args.private is True,
                "checkpoint_and_final_push_enabled": True,
                "durable_terminal_receipt_required": True,
                "observed_cuda_driver_runtime_and_libraries_required": True,
                "reviewed_plan_path_hash_replay_required": True,
            },
        }
    )
    write_json(out / "handoff.json", handoff)
    (out / "README.md").write_text(
        "# Hugging Face Jobs handoff\n\n"
        "1. Review `payload/reviewed_training_plan.json`, `payload/`, and `handoff.json`.\n"
        "2. With explicit approval, run the recorded `upload_command`.\n"
        "3. Submit `job_request.json` through the Hugging Face Jobs integration.\n"
        "4. Import the immutable remote completion receipt; never treat job exit alone as success.\n"
        "5. Completion and publication receipts must replay the reviewed plan and attest observed "
        "CUDA, driver, runtime, and library identities.\n",
        encoding="utf-8",
    )
    return handoff


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--experiment-dir", type=Path, required=True)
    parser.add_argument("--training-plan", type=Path, required=True)
    parser.add_argument("--model-manifest", type=Path, required=True)
    parser.add_argument("--reviewer", required=True)
    parser.add_argument("--reviewed-at", default="")
    parser.add_argument("--dataset-repo", required=True, help="Private Hugging Face dataset repo")
    parser.add_argument("--hub-model-id", required=True, help="Private Hub model repo for checkpoints, adapter, and receipts")
    parser.add_argument("--mode", choices=sorted({"trace_sft", "fr_sft", "fr_action_sft", "fr_dpo", "fr_sft_dpo"}))
    parser.add_argument("--flavor", default="a10g-large")
    parser.add_argument("--timeout", default="4h")
    parser.add_argument(
        "--container-image",
        required=True,
        help="Execution image pinned as <registry>/<image>@sha256:<digest>",
    )
    parser.add_argument("--dependency", action="append", default=[])
    parser.add_argument("--private", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--resume-revision", default="")
    parser.add_argument("--resume-phase", choices=["", "sft", "dpo"], default="")
    parser.add_argument("--resume-checkpoint-path", default="")
    parser.add_argument("--resume-checkpoint-manifest-sha256", default="")
    parser.add_argument("--out", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    try:
        handoff = prepare(parse_args())
    except (HuggingFaceLifecycleError, OSError, ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(str(exc)) from exc
    print(json.dumps(handoff, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
